[graph]
targets = ["wasm32-unknown-unknown", "x86_64-unknown-linux-gnu"]
all-features = false

[advisories]
ignore = []

[licenses]
confidence-threshold = 0.8
allow = [
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "MIT",
  "Unicode-3.0",
  "Unlicense",
  "Zlib",
]

[licenses.private]
ignore = false

[bans]
multiple-versions = "allow"
wildcards = "deny"
highlight = "simplest-path"
workspace-default-features = "allow"
external-default-features = "allow"
allow-workspace = true

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
